/**
 * Agora RTC Configuration
 */

export const AGORA_CONFIG = {
  appId: import.meta.env.VITE_AGORA_APP_ID || '',
  
  // RTC Client Configuration
  clientConfig: {
    mode: 'rtc' as const, // 'rtc' for real-time communication
    codec: 'vp8' as const, // VP8 video codec
  },

  // Video Encoder Configuration
  videoEncoderConfig: {
    // 640x480 @ 15fps for normal view
    width: 640,
    height: 480,
    frameRate: 15,
    bitrateMin: 400,
    bitrateMax: 1000,
  },

  // Audio Configuration
  audioConfig: {
    // High quality audio
    profile: 'music_standard' as const,
    echoCancellation: true,
    noiseSuppression: true,
    autoGainControl: true,
  },

  // Token Configuration
  tokenConfig: {
    // Token will be generated by backend
    // Token expires in 24 hours
    expirationTimeInSeconds: 86400, // 24 hours
  },
};

/**
 * Generate unique channel name for meeting
 */
export function generateChannelName(connectionId?: string): string {
  const timestamp = Date.now();
  const randomStr = Math.random().toString(36).substring(2, 8);
  
  if (connectionId) {
    return `meeting_${connectionId}_${timestamp}`;
  }
  
  return `meeting_${timestamp}_${randomStr}`;
}

/**
 * Validate Agora App ID
 */
export function validateAppId(): boolean {
  const appId = AGORA_CONFIG.appId;
  
  if (!appId) {
    console.error('❌ Agora App ID is not configured. Please set VITE_AGORA_APP_ID in .env.local');
    return false;
  }
  
  if (appId.length !== 32) {
    console.warn('⚠️ Agora App ID seems invalid (should be 32 characters)');
  }
  
  return true;
}

